#include "BoostedDiTau/MiniAODSkimmer/interface/JetInfoDS.h"
#include "BoostedDiTau/MiniAODSkimmer/interface/MuonInfoDS.h"
#include "BoostedDiTau/MiniAODSkimmer/interface/ElectronInfoDS.h"
#include "BoostedDiTau/MiniAODSkimmer/interface/TauInfoDS.h"
#include "BoostedDiTau/MiniAODSkimmer/interface/GenParticleInfoDS.h"
#include "BoostedDiTau/MiniAODSkimmer/interface/TrigObjectInfoDS.h"
#include "BoostedDiTau/MiniAODSkimmer/interface/PhotonInfoDS.h"
